---
# tasks file for kiosk_mode
- name: Ensure hostname set
  ansible.builtin.hostname:
    name: "{{ inventory_hostname.split('.')[0] }}"

- name: Register as user with password and auto-subscribe to available content.
  community.general.redhat_subscription:
    state: present
    username: "{{ rhsm_username }}"
    password: "{{ rhsm_password }}"
    auto_attach: true

- name: Check package facts
  ansible.builtin.package_facts:

- name: Install Open Telemetry Collector
  ansible.builtin.package:
    name:
      - https://github.com/open-telemetry/opentelemetry-collector-releases/releases/download/v0.114.0/otelcol-contrib_0.114.0_linux_amd64.rpm
    state: present
  when:
    - ansible_facts['packages']['otelcol-contrib'] is not defined

- name: Manage OTEL Config
  ansible.builtin.template:
    src: config.yml.j2
    #dest: /etc/opentelemetry-collector/configs/01-federated-edge-observability.yaml
    dest: /etc/otelcol-contrib/config.yaml
    owner: root
    group: root
    mode: "0644"
  notify: "restart otel-collector"

- name: Manage OTEL Service
  ansible.builtin.service:
    name: "{{ otel_collector_service_name }}"
    state: started
    enabled: true
